export { default as AddFundsModal } from './AddFundsModal'
export { default as ResultsModal } from './ResultsModal'
export { default as RulesModal } from './RulesModal'
export { default as PatternInfoModal } from './PatternInfoModal'
export { default as HistoryModal } from './HistoryModal'
export { default as HomeModal } from './HomeModal'
export { default as LoadingScreen } from './LoadingScreen' 